wh13 done!
eugene-okulik/YanSurmaQa pull request #12
Opened 2024-03-01 14:30 UTC by YanSurma

2024-03-02 11:34 UTC, eugene-okulik requested changes
Мелочь вроде, а не работает.

2024-03-02 11:34 UTC, eugene-okulik commented on homework/yan_surma/homework_13/task.py
> +eugene_file_path = os.path.join(homework_path, 'eugene_okulik\\hw_13', 'data.txt')
У меня не работает. Я на линуксе, у меня слеши такие: /

2024-03-02 17:41 UTC, YanSurma commented
Добавил исправление в коде: eugene_file_path = os.path.join(homework_path, 'eugene_okulik', 'hw_13', 'data.txt')
прописал папку также через join во избежание конфликтов.

2024-03-03 07:59 UTC, eugene-okulik approved these changes

2024-03-03 07:59 UTC, merged