Ys homework 4
eugene-okulik/YanSurmaQa pull request #3
Opened 2024-02-14 12:50 UTC by YanSurma

2024-02-15 09:38 UTC, eugene-okulik requested changes

2024-02-15 09:38 UTC, eugene-okulik commented on homework/yan_surma/homework_4/create_dict.py
> +my_list.pop(2)  # 'hello'
Нужно было удалить второе, а ты удаляешь  то, которое со значением 2. Если там будет другое значение, то не понятно что удалится.

2024-02-15 09:38 UTC, eugene-okulik commented on homework/yan_surma/homework_4/create_dict.py
> +my_dict['i am a tuple'] = 'random value'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А у тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

текст ключа намекает на то, чем должен быть этот ключ.

2024-02-15 10:21 UTC, YanSurma reviewed
Please check)

2024-02-16 09:37 UTC, eugene-okulik requested changes

2024-02-16 09:37 UTC, eugene-okulik commented on homework/yan_surma/homework_4/create_dict.py
> +popped = my_list.pop(2)  # Fixed: Удаляем по ключу
Отлично, но теперь ты удаляешь третий элемент )))

2024-02-16 09:37 UTC, eugene-okulik commented on homework/yan_surma/homework_4/create_dict.py
> +my_dict['i am a tuple'] = ('cool', 2, 'black', 4, 'pink')  # Fixed: Добавляем tuple
Ключ - всё еще строка

2024-02-16 09:47 UTC, YanSurma commented
check pls)

2024-02-16 09:59 UTC, eugene-okulik approved these changes

2024-02-16 09:59 UTC, merged